### ISSUE TITLE
Add animation to Coin Flip to react-game

### ISSUE THREAD

**Issue by nianokia** [nianokia/techtonica-assignments#9]
### Add animation to Coin Flip component in React Game

I like the idea of making my coin flip, I haven't had the time to learn animation yet so that would be amazing.

[https://github.com/nianokia/techtonica-assignments/blob/main/react-game/src/CoinFlip.jsx](url)

**Comment by Xhz0729** [comment]
Hi! I'd like to work on this issue. Can you please assign it to me? Thanks very much!

**Comment by nianokia** [comment]
Yes, thank you for taking this on! I've assigned the issue to you. @Xhz0729
